# -*- coding: utf-8 -*-
"""ViniciusLisboaPorto_RM561406_Fase3_cap10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbPrGJGpWvm7ErSf4sjFmATBGYex57u8

# Análise Preditiva de Culturas Agrícolas

**Integrantes do Grupo:**
- Vinicius de Santana Gama - RM566672
- Pedro Carvalho Rocha Lima - RM567330
- Vinicius Lisboa Porto - RM561406
- Marlon Paulino Marinho - RM566793
- Danilo Marques Dantas - RM567583

**Objetivo:** Analisar condições de solo e clima para prever qual cultura agrícola é mais adequada para plantio, desenvolvendo modelos preditivos e identificando perfis ideais de cultivo.

---

## 1. Importação de Bibliotecas e Carregamento dos Dados
"""

# Bibliotecas fundamentais
import pandas as pd
import numpy as np
import os
import matplotlib
matplotlib.use("Agg")  # gera as imagens como PNG, sem janelas que travam o script
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')

# Bibliotecas para Machine Learning
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

# Algoritmos de classificação
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Configurações de visualização
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10

# Pasta onde os gráficos gerados são salvos (ao lado deste script)
GRAF_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "graficos")
os.makedirs(GRAF_DIR, exist_ok=True)
_graf_paths = []
_graf_count = 0
_GRAF_NOMES = [
    "01_distribuicao_variaveis", "02_matriz_correlacao", "03_boxplot_npk",
    "04_temperatura_umidade", "05_ph_precipitacao", "06_comparacao_culturas",
    "07_comparacao_modelos", "08_matriz_confusao",
]


def salvar_grafico():
    """Salva a figura atual em graficos/ e a fecha.

    Substitui salvar_grafico(): com o backend Agg as janelas não abririam de qualquer
    forma, e o show() interativo travava o script esperando o usuário fechar
    cada janela. Aqui cada gráfico vira um arquivo PNG que pode ser aberto depois.
    """
    global _graf_count
    nome = _GRAF_NOMES[_graf_count] if _graf_count < len(_GRAF_NOMES) else f"extra_{_graf_count}"
    _graf_count += 1
    caminho = os.path.join(GRAF_DIR, nome + ".png")
    plt.savefig(caminho, dpi=120, bbox_inches="tight")
    plt.close()
    _graf_paths.append(caminho)
    print(f"  🖼️  Gráfico salvo: {caminho}")


print("✓ Bibliotecas importadas com sucesso")

# Carregamento da base de dados
df = pd.read_csv('produtos_agricolas.csv')

print("Base de dados carregada com sucesso!")
print(f"Dimensões: {df.shape[0]} registros × {df.shape[1]} variáveis")

"""---
## 2. Análise Exploratória dos Dados

Nesta etapa inicial, vamos conhecer a estrutura da base, identificar padrões básicos e verificar a qualidade dos dados.
"""

# Visualização das primeiras linhas
print("=" * 80)
print("PRIMEIRAS LINHAS DA BASE")
print("=" * 80)
print(df.head(10))

# Informações gerais sobre a base
print("=" * 80)
print("INFORMAÇÕES GERAIS")
print("=" * 80)
print(f"\nDimensões: {df.shape[0]} linhas × {df.shape[1]} colunas")
print(f"\nVariáveis numéricas: N, P, K, temperature, humidity, ph, rainfall")
print(f"Variável categórica (target): label (tipo de cultura)")
print(f"\nMemória utilizada: {df.memory_usage(deep=True).sum() / 1024:.2f} KB")

# Tipos de dados e valores ausentes
print("\n" + "=" * 80)
print("QUALIDADE DOS DADOS")
print("=" * 80)

info_df = pd.DataFrame({
    'Tipo': df.dtypes,
    'Valores Ausentes': df.isnull().sum(),
    '% Ausentes': (df.isnull().sum() / len(df) * 100).round(2)
})
print(info_df)

print("\n✓ Base de dados completa: nenhum valor ausente encontrado")

# Distribuição das culturas
print("\n" + "=" * 80)
print("DISTRIBUIÇÃO DAS CULTURAS")
print("=" * 80)

culturas_count = df['label'].value_counts().sort_index()
print(f"\nTotal de culturas diferentes: {df['label'].nunique()}")
print(f"\nDistribuição dos registros:")
for cultura, count in culturas_count.items():
    print(f"  • {cultura.capitalize()}: {count} registros ({count/len(df)*100:.1f}%)")

print("\n✓ Base balanceada: cada cultura possui exatamente 100 registros")

# Estatísticas descritivas das variáveis numéricas
print("\n" + "=" * 80)
print("ESTATÍSTICAS DESCRITIVAS DAS VARIÁVEIS AMBIENTAIS E DE SOLO")
print("=" * 80)

stats_desc = df.describe().round(2)
print(stats_desc)

print("\nInterpretação:")
print("  • N (Nitrogênio): varia de 0 a 140 kg/ha, média de 50.55 kg/ha")
print("  • P (Fósforo): varia de 5 a 145 kg/ha, média de 53.36 kg/ha")
print("  • K (Potássio): varia de 5 a 205 kg/ha, média de 48.15 kg/ha")
print("  • Temperature: varia de 8.83°C a 43.68°C, média de 25.62°C")
print("  • Humidity: varia de 14.26% a 99.98%, média de 71.48%")
print("  • pH: varia de 3.50 a 9.94, média de 6.47 (levemente ácido)")
print("  • Rainfall: varia de 20.21mm a 298.56mm, média de 103.46mm")

"""---
## 3. Análise Descritiva com Visualizações

Aqui vamos explorar visualmente os padrões nos dados através de gráficos que revelam relações importantes entre as variáveis.

### 3.1. Gráfico 1: Distribuição das Variáveis Ambientais
"""

# Gráfico 1: Histogramas das variáveis numéricas
fig, axes = plt.subplots(2, 4, figsize=(16, 8))
fig.suptitle('Distribuição das Variáveis Ambientais e de Solo', fontsize=16, fontweight='bold')

variaveis = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
titulos = ['Nitrogênio (N)', 'Fósforo (P)', 'Potássio (K)', 'Temperatura (°C)',
           'Umidade (%)', 'pH do Solo', 'Precipitação (mm)']

for idx, (var, titulo) in enumerate(zip(variaveis, titulos)):
    row = idx // 4
    col = idx % 4
    axes[row, col].hist(df[var], bins=30, color='steelblue', edgecolor='black', alpha=0.7)
    axes[row, col].set_title(titulo, fontweight='bold')
    axes[row, col].set_xlabel('Valor')
    axes[row, col].set_ylabel('Frequência')
    axes[row, col].axvline(df[var].mean(), color='red', linestyle='--', linewidth=2, label=f'Média: {df[var].mean():.1f}')
    axes[row, col].legend()

# Remover subplot extra
fig.delaxes(axes[1, 3])

plt.tight_layout()
salvar_grafico()

print("\nInsights do Gráfico 1:")
print("  • Nitrogênio: distribuição bimodal, indicando grupos de culturas com baixa e alta demanda")
print("  • Temperatura: distribuição próxima à normal, concentrada entre 20-30°C")
print("  • pH: distribuição levemente assimétrica, maioria dos solos são neutros a levemente ácidos")
print("  • Precipitação: grande variabilidade, refletindo diferentes necessidades hídricas")

"""### 3.2. Gráfico 2: Matriz de Correlação"""

# Gráfico 2: Matriz de correlação
plt.figure(figsize=(10, 8))
correlation_matrix = df[variaveis].corr()

sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação entre Variáveis Ambientais e de Solo',
          fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
salvar_grafico()

print("\nInsights do Gráfico 2:")
print("  • Baixa correlação entre as variáveis (máximo ~0.3), indicando independência")
print("  • Não há multicolinearidade significativa, bom para modelos preditivos")
print("  • Cada variável contribui com informação única sobre as condições de cultivo")
print("  • Isso sugere que todas as 7 variáveis são relevantes para a previsão")

"""### 3.3. Gráfico 3: Boxplot - Nutrientes por Cultura"""

# Gráfico 3: Boxplot dos nutrientes NPK
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Distribuição de Nutrientes (N-P-K) por Cultura', fontsize=16, fontweight='bold')

nutrientes = ['N', 'P', 'K']
nomes_nutrientes = ['Nitrogênio (N)', 'Fósforo (P)', 'Potássio (K)']

for idx, (nutriente, nome) in enumerate(zip(nutrientes, nomes_nutrientes)):
    sns.boxplot(data=df, y='label', x=nutriente, ax=axes[idx], palette='Set2')
    axes[idx].set_title(nome, fontweight='bold')
    axes[idx].set_xlabel(f'{nutriente} (kg/ha)')
    axes[idx].set_ylabel('')

plt.tight_layout()
salvar_grafico()

print("\nInsights do Gráfico 3:")
print("  • Culturas apresentam demandas nutricionais muito distintas")
print("  • Algodão (cotton) e café (coffee) requerem alto N, P e K")
print("  • Arroz (rice) e leguminosas precisam de alto N")
print("  • Frutas geralmente demandam níveis moderados de nutrientes")
print("  • A variação nutricional é um forte preditor do tipo de cultura")

"""### 3.4. Gráfico 4: Condições Climáticas por Cultura"""

# Gráfico 4: Scatter plot - Temperatura vs Umidade por Cultura
plt.figure(figsize=(14, 8))
culturas_unicas = df['label'].unique()
cores = sns.color_palette('tab20', n_colors=len(culturas_unicas))

for idx, cultura in enumerate(sorted(culturas_unicas)):
    dados_cultura = df[df['label'] == cultura]
    plt.scatter(dados_cultura['temperature'], dados_cultura['humidity'],
                label=cultura.capitalize(), alpha=0.6, s=50, color=cores[idx])

plt.xlabel('Temperatura (°C)', fontsize=12, fontweight='bold')
plt.ylabel('Umidade (%)', fontsize=12, fontweight='bold')
plt.title('Relação entre Temperatura e Umidade por Cultura', fontsize=14, fontweight='bold')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', ncol=2)
plt.grid(True, alpha=0.3)
plt.tight_layout()
salvar_grafico()

print("\nInsights do Gráfico 4:")
print("  • Culturas formam clusters distintos no espaço temperatura-umidade")
print("  • Arroz: alta umidade (>80%) e temperatura moderada")
print("  • Café e algodão: temperatura elevada (>22°C) e umidade variável")
print("  • Leguminosas: preferem baixa umidade (<60%)")
print("  • A separação visual indica alta previsibilidade baseada nessas variáveis")

"""### 3.5. Gráfico 5: Precipitação e pH - Análise Comparativa"""

# Gráfico 5: Violin plot - pH e Precipitação
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Distribuição de pH e Precipitação por Cultura', fontsize=16, fontweight='bold')

# Selecionar culturas com maior variação para melhor visualização
culturas_selecionadas = ['rice', 'maize', 'cotton', 'coffee', 'chickpea',
                          'kidneybeans', 'banana', 'mango', 'coconut', 'grapes']
df_filtrado = df[df['label'].isin(culturas_selecionadas)]

# pH
sns.violinplot(data=df_filtrado, y='label', x='ph', ax=axes[0], palette='muted')
axes[0].set_title('pH do Solo', fontweight='bold')
axes[0].set_xlabel('pH')
axes[0].set_ylabel('')
axes[0].axvline(7, color='red', linestyle='--', linewidth=1.5, alpha=0.5, label='pH Neutro')
axes[0].legend()

# Precipitação
sns.violinplot(data=df_filtrado, y='label', x='rainfall', ax=axes[1], palette='muted')
axes[1].set_title('Precipitação', fontweight='bold')
axes[1].set_xlabel('Precipitação (mm)')
axes[1].set_ylabel('')

plt.tight_layout()
salvar_grafico()

print("\nInsights do Gráfico 5:")
print("  • Arroz: requer alta precipitação (>200mm) e pH neutro a levemente ácido")
print("  • Café: tolera ampla faixa de pH (5-7) e precipitação moderada")
print("  • Algodão: prefere pH próximo ao neutro e precipitação moderada a baixa")
print("  • Leguminosas: adaptadas a baixa precipitação (<70mm) e solos alcalinos")
print("  • Frutas tropicais: demandam pH ácido e alta precipitação")

"""---
## 4. Perfil Ideal de Solo e Clima

Nesta seção, vamos calcular o perfil médio ideal para cada variável e comparar como as três culturas escolhidas pelo grupo (Milho, Café e Algodão) se posicionam em relação a esse perfil.
"""

# Cálculo do perfil ideal (valores médios globais)
perfil_ideal = df[variaveis].mean()

print("=" * 80)
print("PERFIL IDEAL DE SOLO E CLIMA (MÉDIAS GLOBAIS)")
print("=" * 80)
print(f"\nNitrogênio (N): {perfil_ideal['N']:.2f} kg/ha")
print(f"Fósforo (P): {perfil_ideal['P']:.2f} kg/ha")
print(f"Potássio (K): {perfil_ideal['K']:.2f} kg/ha")
print(f"Temperatura: {perfil_ideal['temperature']:.2f}°C")
print(f"Umidade: {perfil_ideal['humidity']:.2f}%")
print(f"pH: {perfil_ideal['ph']:.2f}")
print(f"Precipitação: {perfil_ideal['rainfall']:.2f} mm")

print("\n" + "=" * 80)
print("Interpretação do Perfil Ideal:")
print("=" * 80)
print("Este perfil representa as condições médias encontradas na base de dados.")
print("Culturas que se aproximam desses valores possuem maior flexibilidade de cultivo,")
print("enquanto culturas com valores extremos possuem necessidades mais específicas.")

"""### 4.1. Análise Comparativa: Milho, Café e Algodão"""

# Perfis específicos das culturas selecionadas
culturas_grupo = ['maize', 'coffee', 'cotton']
nomes_portugues = ['Milho', 'Café', 'Algodão']

print("\n" + "=" * 80)
print("PERFIS DAS CULTURAS SELECIONADAS")
print("=" * 80)

perfis_culturas = {}
for cultura, nome_pt in zip(culturas_grupo, nomes_portugues):
    perfil = df[df['label'] == cultura][variaveis].mean()
    perfis_culturas[nome_pt] = perfil

    print(f"\n{nome_pt.upper()} ({cultura})")
    print("-" * 80)
    for var in variaveis:
        print(f"  {var:12s}: {perfil[var]:7.2f}")

# Criar DataFrame comparativo
df_comparacao = pd.DataFrame(perfis_culturas)
df_comparacao['Perfil Ideal'] = perfil_ideal

print("\n" + "=" * 80)
print("TABELA COMPARATIVA")
print("=" * 80)
print(df_comparacao.round(2))

# Visualização comparativa
fig, axes = plt.subplots(2, 4, figsize=(18, 10))
fig.suptitle('Comparação entre Milho, Café, Algodão e Perfil Ideal',
             fontsize=16, fontweight='bold')

for idx, var in enumerate(variaveis):
    row = idx // 4
    col = idx % 4
    ax = axes[row, col]

    # Dados para o gráfico
    valores = [df_comparacao.loc[var, 'Milho'],
               df_comparacao.loc[var, 'Café'],
               df_comparacao.loc[var, 'Algodão'],
               df_comparacao.loc[var, 'Perfil Ideal']]

    categorias = ['Milho', 'Café', 'Algodão', 'Ideal']
    cores = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']

    bars = ax.bar(categorias, valores, color=cores, alpha=0.7, edgecolor='black')
    ax.set_title(var.upper(), fontweight='bold')
    ax.set_ylabel('Valor')

    # Adicionar valores nas barras
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.1f}', ha='center', va='bottom', fontsize=9)

    ax.tick_params(axis='x', rotation=45)

# Remover subplot extra
fig.delaxes(axes[1, 3])

plt.tight_layout()
salvar_grafico()

"""### 4.2. Análise Detalhada por Cultura"""

# Análise estatística comparativa
print("=" * 80)
print("ANÁLISE COMPARATIVA DETALHADA")
print("=" * 80)

print("\n1. MILHO (Maize)")
print("-" * 80)
print("Características em relação ao perfil ideal:")
milho_data = df[df['label'] == 'maize'][variaveis]
print(f"  • Nitrogênio: {milho_data['N'].mean():.1f} kg/ha (similar ao ideal: {perfil_ideal['N']:.1f})")
print(f"  • Fósforo: {milho_data['P'].mean():.1f} kg/ha (levemente abaixo do ideal: {perfil_ideal['P']:.1f})")
print(f"  • Potássio: {milho_data['K'].mean():.1f} kg/ha (abaixo do ideal: {perfil_ideal['K']:.1f})")
print(f"  • Temperatura: {milho_data['temperature'].mean():.1f}°C (levemente abaixo do ideal: {perfil_ideal['temperature']:.1f})")
print(f"  • Umidade: {milho_data['humidity'].mean():.1f}% (significativamente abaixo do ideal: {perfil_ideal['humidity']:.1f})")
print(f"  • pH: {milho_data['ph'].mean():.2f} (próximo ao ideal: {perfil_ideal['ph']:.2f})")
print(f"  • Precipitação: {milho_data['rainfall'].mean():.1f} mm (abaixo do ideal: {perfil_ideal['rainfall']:.1f})")
print("\nInterpretação:")
print("  O milho adapta-se bem a condições de umidade moderada a baixa (55-60%),")
print("  preferindo climas mais secos que a média. Demanda nutricional equilibrada,")
print("  especialmente em NPK, e tolera ampla faixa de temperatura.")

print("\n2. CAFÉ (Coffee)")
print("-" * 80)
print("Características em relação ao perfil ideal:")
cafe_data = df[df['label'] == 'coffee'][variaveis]
print(f"  • Nitrogênio: {cafe_data['N'].mean():.1f} kg/ha (MUITO ACIMA do ideal: {perfil_ideal['N']:.1f})")
print(f"  • Fósforo: {cafe_data['P'].mean():.1f} kg/ha (abaixo do ideal: {perfil_ideal['P']:.1f})")
print(f"  • Potássio: {cafe_data['K'].mean():.1f} kg/ha (abaixo do ideal: {perfil_ideal['K']:.1f})")
print(f"  • Temperatura: {cafe_data['temperature'].mean():.1f}°C (similar ao ideal: {perfil_ideal['temperature']:.1f})")
print(f"  • Umidade: {cafe_data['humidity'].mean():.1f}% (abaixo do ideal: {perfil_ideal['humidity']:.1f})")
print(f"  • pH: {cafe_data['ph'].mean():.2f} (similar ao ideal: {perfil_ideal['ph']:.2f})")
print(f"  • Precipitação: {cafe_data['rainfall'].mean():.1f} mm (MUITO ACIMA do ideal: {perfil_ideal['rainfall']:.1f})")
print("\nInterpretação:")
print("  O café é uma cultura exigente em nitrogênio (100+ kg/ha), necessitando de")
print("  fertilização intensiva. Prefere alta precipitação (>150mm) e temperatura")
print("  moderada constante. A umidade intermediária (50-65%) é ideal para sua produção.")

print("\n3. ALGODÃO (Cotton)")
print("-" * 80)
print("Características em relação ao perfil ideal:")
algodao_data = df[df['label'] == 'cotton'][variaveis]
print(f"  • Nitrogênio: {algodao_data['N'].mean():.1f} kg/ha (MUITO ACIMA do ideal: {perfil_ideal['N']:.1f})")
print(f"  • Fósforo: {algodao_data['P'].mean():.1f} kg/ha (acima do ideal: {perfil_ideal['P']:.1f})")
print(f"  • Potássio: {algodao_data['K'].mean():.1f} kg/ha (abaixo do ideal: {perfil_ideal['K']:.1f})")
print(f"  • Temperatura: {algodao_data['temperature'].mean():.1f}°C (acima do ideal: {perfil_ideal['temperature']:.1f})")
print(f"  • Umidade: {algodao_data['humidity'].mean():.1f}% (MUITO ACIMA do ideal: {perfil_ideal['humidity']:.1f})")
print(f"  • pH: {algodao_data['ph'].mean():.2f} (levemente acima do ideal: {perfil_ideal['ph']:.2f})")
print(f"  • Precipitação: {algodao_data['rainfall'].mean():.1f} mm (levemente acima do ideal: {perfil_ideal['rainfall']:.1f})")
print("\nInterpretação:")
print("  O algodão destaca-se por sua demanda extrema de nutrientes, especialmente N e P,")
print("  e por preferir temperaturas elevadas (>25°C) e alta umidade (>80%). Requer")
print("  condições tropicais/subtropicais com precipitação generosa e solo alcalino.")

# Cálculo de distância do perfil ideal (métrica de similaridade)
from scipy.spatial.distance import euclidean

# Normalizar para comparação justa
scaler = StandardScaler()
df_normalizado = pd.DataFrame(
    scaler.fit_transform(df[variaveis]),
    columns=variaveis
)
df_normalizado['label'] = df['label'].values

# Perfil ideal normalizado
perfil_ideal_norm = df_normalizado[variaveis].mean()

# Calcular distância euclidiana média por cultura
distancias = {}
for cultura in culturas_grupo:
    dados_cultura = df_normalizado[df_normalizado['label'] == cultura][variaveis]
    distancia_media = dados_cultura.apply(
        lambda row: euclidean(row, perfil_ideal_norm), axis=1
    ).mean()
    distancias[cultura] = distancia_media

print("\n" + "=" * 80)
print("DISTÂNCIA DO PERFIL IDEAL (quanto menor, mais próximo do ideal)")
print("=" * 80)
for cultura, dist in sorted(distancias.items(), key=lambda x: x[1]):
    nome_pt = dict(zip(culturas_grupo, nomes_portugues))[cultura]
    print(f"  {nome_pt:10s} ({cultura:7s}): {dist:.4f}")

print("\nConclusão:")
cultura_mais_proxima = min(distancias, key=distancias.get)
nome_mais_proxima = dict(zip(culturas_grupo, nomes_portugues))[cultura_mais_proxima]
print(f"  O {nome_mais_proxima} é a cultura mais próxima do perfil ideal,")
print(f"  indicando maior versatilidade de cultivo em diferentes condições.")

"""### 4.3. Síntese Comparativa"""

print("=" * 80)
print("SÍNTESE: COMPARAÇÃO ENTRE MILHO, CAFÉ E ALGODÃO")
print("=" * 80)

print("\n1. DEMANDA NUTRICIONAL (N-P-K)")
print("-" * 80)
print("  Alta demanda: Café e Algodão (especialmente Nitrogênio >100 kg/ha)")
print("  Demanda moderada: Milho (50-60 kg/ha de NPK)")
print("\n  → Café e Algodão requerem fertilização intensiva")
print("  → Milho é mais econômico em termos de insumos")

print("\n2. CONDIÇÕES CLIMÁTICAS")
print("-" * 80)
print("  Temperatura:")
print("    • Algodão prefere CALOR (>25°C)")
print("    • Café e Milho adaptam-se bem a temperaturas moderadas (23-25°C)")
print("\n  Umidade:")
print("    • Algodão requer ALTA umidade (>80%)")
print("    • Café tolera umidade moderada (50-65%)")
print("    • Milho prefere BAIXA umidade (<60%)")
print("\n  Precipitação:")
print("    • Café demanda ALTA precipitação (>150mm)")
print("    • Algodão requer precipitação moderada-alta (>100mm)")
print("    • Milho adapta-se a BAIXA precipitação (<70mm)")

print("\n3. CARACTERÍSTICAS DE SOLO")
print("-" * 80)
print("  pH:")
print("    • Algodão prefere solos ALCALINOS (pH 6.8-7.5)")
print("    • Café tolera solos NEUTROS a levemente ácidos (pH 6.2-6.5)")
print("    • Milho adapta-se bem a solos NEUTROS (pH 6.2-6.5)")

print("\n4. PERFIL DE CULTIVO")
print("-" * 80)
print("  MILHO: Cultura versátil, baixa demanda hídrica e nutricional moderada")
print("         → Ideal para regiões de clima seco e recursos limitados")
print("\n  CAFÉ: Exigente em nitrogênio e água, temperatura constante")
print("        → Ideal para regiões tropicais de altitude com boa precipitação")
print("\n  ALGODÃO: Alta demanda de nutrientes, calor e umidade")
print("           → Ideal para regiões tropicais úmidas com fertilização intensiva")

print("\n" + "=" * 80)

"""---
## 5. Desenvolvimento de Modelos Preditivos

Vamos desenvolver 5 modelos de Machine Learning diferentes para prever qual cultura é mais adequada dadas as condições de solo e clima.

### 5.1. Preparação dos Dados
"""

# Separação de features e target
X = df[variaveis]
y = df['label']

print("=" * 80)
print("PREPARAÇÃO DOS DADOS PARA MODELAGEM")
print("=" * 80)
print(f"\nFeatures (X): {X.shape}")
print(f"Target (y): {y.shape}")
print(f"\nVariáveis preditoras: {list(X.columns)}")
print(f"Número de classes: {y.nunique()}")

# Divisão treino-teste com estratificação
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nDivisão realizada:")
print(f"  • Conjunto de treino: {X_train.shape[0]} amostras ({X_train.shape[0]/len(X)*100:.1f}%)")
print(f"  • Conjunto de teste: {X_test.shape[0]} amostras ({X_test.shape[0]/len(X)*100:.1f}%)")
print(f"\n✓ Estratificação aplicada para manter proporção de classes")

# Normalização dos dados
scaler_model = StandardScaler()
X_train_scaled = scaler_model.fit_transform(X_train)
X_test_scaled = scaler_model.transform(X_test)

print("\n✓ Normalização aplicada (StandardScaler)")
print("  Importante para algoritmos sensíveis à escala (KNN, SVM)")

"""### 5.2. Modelo 1: Random Forest"""

# Aviso de tempo: o treino dos 5 modelos (com validação cruzada) é a etapa
# mais lenta — o Gradient Boosting sozinho leva ~2 min. Sem este aviso o
# usuário acha que travou. flush=True garante que apareça imediatamente.
_t_treino = time.time()
print("\n" + "█" * 64)
print("  ⏳  TREINANDO OS MODELOS DE MACHINE LEARNING — AGUARDE")
print("      Tempo estimado: cerca de 2 a 3 minutos.")
print("      A tela vai parecer PARADA no 'MODELO 2' (Gradient Boosting):")
print("      isso é normal, ele é o mais demorado. NÃO feche a janela.")
print("      Ao terminar, os gráficos são salvos e a pasta abre sozinha.")
print("█" * 64, flush=True)

print("\n" + "=" * 80)
print("MODELO 1: RANDOM FOREST")
print("=" * 80)
print("\nCaracterísticas:")
print("  • Ensemble de múltiplas árvores de decisão")
print("  • Robusto a overfitting e outliers")
print("  • Fornece importância das features")
print("  • Não requer normalização dos dados")

# Treinamento
rf_model = RandomForestClassifier(
    n_estimators=150,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Avaliação
acc_rf = accuracy_score(y_test, y_pred_rf)
print(f"\n✓ Acurácia no conjunto de teste: {acc_rf*100:.2f}%")

# Cross-validation
cv_scores_rf = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy')
print(f"✓ Acurácia média (5-fold CV): {cv_scores_rf.mean()*100:.2f}% (±{cv_scores_rf.std()*100:.2f}%)")

# Importância das features
importancias_rf = pd.DataFrame({
    'Feature': X.columns,
    'Importância': rf_model.feature_importances_
}).sort_values('Importância', ascending=False)

print("\nImportância das Features:")
for idx, row in importancias_rf.iterrows():
    print(f"  {row['Feature']:12s}: {row['Importância']:.4f}")

"""### 5.3. Modelo 2: Gradient Boosting"""

print("\n" + "=" * 80)
print("MODELO 2: GRADIENT BOOSTING")
print("=" * 80)
print("\nCaracterísticas:")
print("  • Construção sequencial de árvores fracas")
print("  • Cada árvore corrige erros da anterior")
print("  • Alta performance, mas mais lento para treinar")
print("  • Sensível a hiperparâmetros")

# Este é o gargalo (~2 min). Avisa e mostra o tempo decorrido ao terminar.
print("\n  ⏳  ESTE É O MODELO MAIS DEMORADO (~2 minutos).")
print("      Treinando agora... a tela fica parada de propósito. Aguarde.",
      flush=True)

# Treinamento
gb_model = GradientBoostingClassifier(
    n_estimators=120,
    learning_rate=0.1,
    max_depth=8,
    min_samples_split=5,
    min_samples_leaf=2,
    subsample=0.8,
    random_state=42
)

gb_model.fit(X_train, y_train)
y_pred_gb = gb_model.predict(X_test)

# Avaliação
acc_gb = accuracy_score(y_test, y_pred_gb)
print(f"\n✓ Acurácia no conjunto de teste: {acc_gb*100:.2f}%")

# Cross-validation
cv_scores_gb = cross_val_score(gb_model, X_train, y_train, cv=5, scoring='accuracy')
print(f"✓ Acurácia média (5-fold CV): {cv_scores_gb.mean()*100:.2f}% (±{cv_scores_gb.std()*100:.2f}%)")
print(f"\n  ✅  Parte demorada concluída em {time.time() - _t_treino:.0f}s. "
      "Falta pouco — gerando os gráficos finais...", flush=True)

"""### 5.4. Modelo 3: Decision Tree"""

print("\n" + "=" * 80)
print("MODELO 3: DECISION TREE (ÁRVORE DE DECISÃO)")
print("=" * 80)
print("\nCaracterísticas:")
print("  • Estrutura de árvore com regras if-then-else")
print("  • Fácil interpretação e visualização")
print("  • Tende a overfitting sem poda adequada")
print("  • Rápido para treinar e prever")

# Treinamento
dt_model = DecisionTreeClassifier(
    max_depth=15,
    min_samples_split=8,
    min_samples_leaf=3,
    criterion='gini',
    random_state=42
)

dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

# Avaliação
acc_dt = accuracy_score(y_test, y_pred_dt)
print(f"\n✓ Acurácia no conjunto de teste: {acc_dt*100:.2f}%")

# Cross-validation
cv_scores_dt = cross_val_score(dt_model, X_train, y_train, cv=5, scoring='accuracy')
print(f"✓ Acurácia média (5-fold CV): {cv_scores_dt.mean()*100:.2f}% (±{cv_scores_dt.std()*100:.2f}%)")

"""### 5.5. Modelo 4: K-Nearest Neighbors (KNN)"""

print("\n" + "=" * 80)
print("MODELO 4: K-NEAREST NEIGHBORS (KNN)")
print("=" * 80)
print("\nCaracterísticas:")
print("  • Classificação baseada em proximidade")
print("  • Não paramétrico (não faz suposições sobre distribuição)")
print("  • Sensível à escala (requer normalização)")
print("  • Lento para grandes datasets")

# Treinamento (usando dados normalizados)
knn_model = KNeighborsClassifier(
    n_neighbors=7,
    weights='distance',
    metric='minkowski',
    p=2,
    n_jobs=-1
)

knn_model.fit(X_train_scaled, y_train)
y_pred_knn = knn_model.predict(X_test_scaled)

# Avaliação
acc_knn = accuracy_score(y_test, y_pred_knn)
print(f"\n✓ Acurácia no conjunto de teste: {acc_knn*100:.2f}%")

# Cross-validation
cv_scores_knn = cross_val_score(knn_model, X_train_scaled, y_train, cv=5, scoring='accuracy')
print(f"✓ Acurácia média (5-fold CV): {cv_scores_knn.mean()*100:.2f}% (±{cv_scores_knn.std()*100:.2f}%)")

"""### 5.6. Modelo 5: Support Vector Machine (SVM)"""

print("\n" + "=" * 80)
print("MODELO 5: SUPPORT VECTOR MACHINE (SVM)")
print("=" * 80)
print("\nCaracterísticas:")
print("  • Busca hiperplano ótimo de separação")
print("  • Eficaz em espaços de alta dimensionalidade")
print("  • Kernel RBF permite separação não-linear")
print("  • Computacionalmente intensivo para grandes datasets")

# Treinamento (usando dados normalizados)
svm_model = SVC(
    C=10,
    kernel='rbf',
    gamma='scale',
    random_state=42,
    cache_size=1000
)

svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

# Avaliação
acc_svm = accuracy_score(y_test, y_pred_svm)
print(f"\n✓ Acurácia no conjunto de teste: {acc_svm*100:.2f}%")

# Cross-validation
cv_scores_svm = cross_val_score(svm_model, X_train_scaled, y_train, cv=5, scoring='accuracy')
print(f"✓ Acurácia média (5-fold CV): {cv_scores_svm.mean()*100:.2f}% (±{cv_scores_svm.std()*100:.2f}%)")

"""---
## 6. Comparação de Performance dos Modelos
"""

# Compilar resultados
resultados = pd.DataFrame({
    'Modelo': ['Random Forest', 'Gradient Boosting', 'Decision Tree', 'KNN', 'SVM'],
    'Acurácia Teste': [acc_rf, acc_gb, acc_dt, acc_knn, acc_svm],
    'Acurácia CV (média)': [
        cv_scores_rf.mean(),
        cv_scores_gb.mean(),
        cv_scores_dt.mean(),
        cv_scores_knn.mean(),
        cv_scores_svm.mean()
    ],
    'Desvio Padrão CV': [
        cv_scores_rf.std(),
        cv_scores_gb.std(),
        cv_scores_dt.std(),
        cv_scores_knn.std(),
        cv_scores_svm.std()
    ]
})

resultados['Acurácia Teste'] = (resultados['Acurácia Teste'] * 100).round(2)
resultados['Acurácia CV (média)'] = (resultados['Acurácia CV (média)'] * 100).round(2)
resultados['Desvio Padrão CV'] = (resultados['Desvio Padrão CV'] * 100).round(2)

resultados = resultados.sort_values('Acurácia Teste', ascending=False).reset_index(drop=True)

print("=" * 80)
print("COMPARAÇÃO DE PERFORMANCE DOS MODELOS")
print("=" * 80)
print(resultados)

melhor_modelo = resultados.iloc[0]['Modelo']
melhor_acc = resultados.iloc[0]['Acurácia Teste']
print(f"\n🏆 Melhor modelo: {melhor_modelo} com {melhor_acc:.2f}% de acurácia")

# Visualização comparativa
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Gráfico 1: Acurácia no teste
cores_barras = ['#2E86AB' if modelo == melhor_modelo else '#A9A9A9'
                for modelo in resultados['Modelo']]
axes[0].barh(resultados['Modelo'], resultados['Acurácia Teste'], color=cores_barras, edgecolor='black')
axes[0].set_xlabel('Acurácia (%)', fontweight='bold')
axes[0].set_title('Acurácia no Conjunto de Teste', fontweight='bold')
axes[0].set_xlim([90, 100])
for i, v in enumerate(resultados['Acurácia Teste']):
    axes[0].text(v + 0.2, i, f'{v:.2f}%', va='center')

# Gráfico 2: Acurácia CV com desvio padrão
x_pos = np.arange(len(resultados))
axes[1].bar(x_pos, resultados['Acurácia CV (média)'],
            yerr=resultados['Desvio Padrão CV'],
            color=cores_barras, edgecolor='black',
            capsize=5, alpha=0.7)
axes[1].set_xticks(x_pos)
axes[1].set_xticklabels(resultados['Modelo'], rotation=45, ha='right')
axes[1].set_ylabel('Acurácia (%)', fontweight='bold')
axes[1].set_title('Acurácia com Cross-Validation (5-fold)', fontweight='bold')
axes[1].set_ylim([90, 100])

plt.tight_layout()
salvar_grafico()

print("\nInsights:")
print(f"  • {melhor_modelo} demonstra a melhor performance geral")
print("  • Todos os modelos apresentam acurácia superior a 95%")
print("  • Baixo desvio padrão indica estabilidade dos modelos")
print("  • A separação das culturas é bem definida nos dados")

"""### 6.1. Métricas Detalhadas do Melhor Modelo"""

# Análise detalhada do melhor modelo (Random Forest)
print("=" * 80)
print(f"ANÁLISE DETALHADA: {melhor_modelo.upper()}")
print("=" * 80)

# Classification Report
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_rf, zero_division=0))

# Métricas agregadas
precision_macro = precision_score(y_test, y_pred_rf, average='macro', zero_division=0)
recall_macro = recall_score(y_test, y_pred_rf, average='macro', zero_division=0)
f1_macro = f1_score(y_test, y_pred_rf, average='macro', zero_division=0)

print(f"\nMétricas Macro-Averaged:")
print(f"  • Precisão: {precision_macro*100:.2f}%")
print(f"  • Recall: {recall_macro*100:.2f}%")
print(f"  • F1-Score: {f1_macro*100:.2f}%")

# Matriz de Confusão
cm = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(14, 12))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=sorted(df['label'].unique()),
            yticklabels=sorted(df['label'].unique()),
            cbar_kws={'label': 'Quantidade de Predições'})

plt.title(f'Matriz de Confusão - {melhor_modelo}', fontsize=14, fontweight='bold', pad=20)
plt.ylabel('Classe Real', fontweight='bold')
plt.xlabel('Classe Prevista', fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
salvar_grafico()

print("\nInterpretação da Matriz de Confusão:")
print("  • Diagonal principal (azul escuro): predições corretas")
print("  • Células fora da diagonal: erros de classificação")
print("  • Modelo demonstra alta precisão em todas as classes")
print("  • Poucos casos de confusão entre culturas similares")

"""---
## 7. Conclusões e Limitações

Nesta seção final, consolidamos os principais achados do estudo e discutimos as limitações encontradas.

### 7.1. Principais Achados
"""

print("=" * 80)
print("PRINCIPAIS ACHADOS DO ESTUDO")
print("=" * 80)

print("\n1. QUALIDADE E ESTRUTURA DOS DADOS")
print("-" * 80)
print(f"  • Base de dados completa e balanceada: {df.shape[0]} registros, 22 culturas")
print("  • Nenhum valor ausente ou inconsistente")
print("  • Cada cultura possui exatamente 100 registros (4,5% cada)")
print("  • 7 variáveis preditoras com baixa correlação entre si (independência)")
print("  • Distribuições variadas refletem diversidade de condições agrícolas")

print("\n2. ANÁLISE DO PERFIL IDEAL E COMPARAÇÃO (MILHO, CAFÉ, ALGODÃO)")
print("-" * 80)
print("  • Perfil ideal representa condições médias globais")
print("  • Milho: cultura versátil, próxima do ideal, baixa demanda hídrica")
print("  • Café: alta demanda de nitrogênio (>100 kg/ha) e precipitação (>150mm)")
print("  • Algodão: extrema demanda nutricional e preferência por calor e umidade")
print("  • Cada cultura possui assinatura única de solo-clima")
print("  • Variação ambiental é determinante para escolha da cultura")

print("\n3. PERFORMANCE DOS MODELOS PREDITIVOS")
print("-" * 80)
acc_list = [acc_rf, acc_gb, acc_dt, acc_knn, acc_svm]
print(f"  • Todos os modelos alcançaram acurácia > 95% no teste")
print(f"  • Melhor modelo: {melhor_modelo} ({melhor_acc:.2f}%)")
print(f"  • Acurácia média dos 5 modelos: {np.mean(acc_list)*100:.2f}%")
print(f"  • Baixa variância entre modelos indica dados bem estruturados")
print(f"  • Cross-validation confirma robustez (baixo desvio padrão)")
print("  • Random Forest e Gradient Boosting foram os mais eficazes")

print("\n4. IMPORTÂNCIA DAS VARIÁVEIS (RANDOM FOREST)")
print("-" * 80)
print("  Top 3 variáveis mais importantes:")
for idx, row in importancias_rf.head(3).iterrows():
    print(f"    {idx+1}. {row['Feature']:12s}: {row['Importância']:.4f}")
print("  • Todas as 7 variáveis contribuem significativamente")
print("  • Nutrientes (NPK) e fatores climáticos são igualmente relevantes")

print("\n5. APLICABILIDADE PRÁTICA")
print("-" * 80)
print("  • Modelos podem auxiliar agricultores na tomada de decisão")
print("  • Previsão rápida e precisa do tipo de cultura mais adequado")
print("  • Redução de custos com plantios inadequados")
print("  • Otimização do uso de recursos naturais e insumos")
print("  • Potencial para integração em sistemas de agricultura de precisão")

"""### 7.2. Limitações do Estudo"""

print("\n" + "=" * 80)
print("LIMITAÇÕES E CONSIDERAÇÕES CRÍTICAS")
print("=" * 80)

print("\n1. LIMITAÇÕES DOS DADOS")
print("-" * 80)
print("  • Dataset relativamente pequeno (2.200 registros)")
print("  • Distribuição uniforme pode não refletir realidade de mercado")
print("  • Ausência de dados temporais (sazonalidade, ciclos de cultivo)")
print("  • Falta de informações sobre:")
print("    - Qualidade e textura do solo (arenoso, argiloso, etc.)")
print("    - Topografia e drenagem do terreno")
print("    - Histórico de pragas e doenças")
print("    - Custos de produção e viabilidade econômica")
print("    - Disponibilidade de água para irrigação")
print("  • Não considera variações climáticas extremas")

print("\n2. LIMITAÇÕES DOS MODELOS")
print("-" * 80)
print("  • Modelos assumem condições estáticas (não capturam mudanças temporais)")
print("  • Alta acurácia pode indicar overfitting ao dataset específico")
print("  • Não foram testados hiperparâmetros exaustivamente (devido ao escopo)")
print("  • Modelos são 'caixas pretas' (exceto Decision Tree)")
print("  • Não consideram interações complexas entre variáveis")
print("  • Ausência de validação com dados externos (novos terrenos)")

print("\n3. LIMITAÇÕES PRÁTICAS")
print("-" * 80)
print("  • Coleta de dados de solo/clima pode ser custosa para agricultores")
print("  • Modelos não consideram aspectos logísticos (transporte, armazenamento)")
print("  • Falta de integração com mercado (preços, demanda)")
print("  • Não considera preferências e experiência do agricultor")
print("  • Ausência de análise de risco e retorno financeiro")
print("  • Mudanças climáticas podem afetar previsões futuras")

print("\n4. VIÉS E GENERALIZAÇÃO")
print("-" * 80)
print("  • Dataset pode conter viés geográfico (regiões específicas)")
print("  • Resultados podem não generalizar para todas as regiões do mundo")
print("  • Diferentes cultivares de uma mesma cultura não foram considerados")
print("  • Práticas agronômicas (adubação, irrigação) afetam requisitos reais")

print("\n5. CONSIDERAÇÕES ÉTICAS E SOCIAIS")
print("-" * 80)
print("  • Modelos não substituem conhecimento e experiência de agricultores")
print("  • Decisões devem considerar contexto social e cultural local")
print("  • Importante avaliar impacto ambiental de monoculturas")
print("  • Segurança alimentar e biodiversidade devem ser priorizadas")

"""### 7.3. Recomendações para Trabalhos Futuros"""

print("\n" + "=" * 80)
print("RECOMENDAÇÕES PARA TRABALHOS FUTUROS")
print("=" * 80)

print("\n1. MELHORIA DOS DADOS")
print("-" * 80)
print("  • Coletar mais registros (>10.000) para maior robustez")
print("  • Incluir dados temporais (sazonalidade, anos consecutivos)")
print("  • Adicionar variáveis sobre textura e qualidade do solo")
print("  • Incorporar dados de produtividade real (t/ha)")
print("  • Considerar custos de produção e preços de mercado")

print("\n2. APRIMORAMENTO DOS MODELOS")
print("-" * 80)
print("  • Testar modelos de ensemble mais sofisticados (XGBoost, LightGBM)")
print("  • Implementar deep learning (redes neurais) para capturar padrões complexos")
print("  • Realizar busca em grid mais ampla de hiperparâmetros")
print("  • Desenvolver modelos multi-output (prever produtividade + cultura)")
print("  • Implementar análise de incerteza nas previsões")

print("\n3. VALIDAÇÃO E DEPLOY")
print("-" * 80)
print("  • Validar modelos com dados de diferentes regiões geográficas")
print("  • Realizar estudos de caso com agricultores reais")
print("  • Desenvolver interface web/mobile para uso prático")
print("  • Integrar com APIs de dados climáticos em tempo real")
print("  • Implementar sistema de feedback para melhoria contínua")

print("\n4. EXPANSÃO DO ESCOPO")
print("-" * 80)
print("  • Incluir análise de viabilidade econômica e ROI")
print("  • Considerar rotação de culturas e consórcio")
print("  • Avaliar impacto ambiental e sustentabilidade")
print("  • Desenvolver recomendações de manejo específicas por cultura")
print("  • Integrar com sensoriamento remoto (imagens de satélite)")

print("\n" + "=" * 80)

"""### 7.4. Conclusão Final"""

print("\n" + "=" * 80)
print("CONCLUSÃO FINAL")
print("=" * 80)

print("""
Este estudo demonstrou a viabilidade de usar Machine Learning para prever o tipo
de cultura agrícola mais adequado com base em condições de solo e clima. Os cinco
modelos desenvolvidos alcançaram performance excepcional (>95% de acurácia), com
destaque para Random Forest e Gradient Boosting.

A análise exploratória revelou que cada cultura possui um "perfil" único de
necessidades ambientais e nutricionais. A comparação entre Milho, Café e Algodão
evidenciou diferenças marcantes:
  • Milho: versatilidade e baixa demanda hídrica
  • Café: alto requerimento de nitrogênio e precipitação
  • Algodão: demanda extrema de nutrientes e preferência por calor

Apesar das limitações identificadas (tamanho do dataset, ausência de variáveis
econômicas e temporais), os resultados são promissores e abrem caminho para
aplicações práticas em agricultura de precisão.

Os modelos desenvolvidos podem servir como ferramenta de apoio à decisão para
agricultores, técnicos e gestores, contribuindo para:
  ✓ Otimização do uso de recursos naturais
  ✓ Redução de custos com plantios inadequados
  ✓ Aumento da produtividade agrícola
  ✓ Promoção de práticas agrícolas sustentáveis

O trabalho evidencia o potencial da Inteligência Artificial no agronegócio,
reforçando a importância de investimentos em pesquisa e desenvolvimento de
tecnologias que tornem a agricultura mais eficiente, sustentável e rentável.
""")

print("=" * 80)
print("FIM DO RELATÓRIO")
print("=" * 80)

# Abre automaticamente a pasta com os gráficos gerados (defina
# FARMTECH_NO_OPEN=1 para desativar, ex.: em execuções automatizadas).
print(f"\n{len(_graf_paths)} gráficos gerados em: {GRAF_DIR}")
for _p in _graf_paths:
    print(f"  • {os.path.basename(_p)}")
if os.environ.get("FARMTECH_NO_OPEN") != "1":
    try:
        os.startfile(GRAF_DIR)  # Windows: abre o Explorer na pasta dos gráficos
        print("\n📂 Pasta de gráficos aberta automaticamente.")
    except (AttributeError, OSError):
        pass  # sistemas sem os.startfile (não-Windows) — só lista os caminhos